import React,{useEffect,useMemo,useRef,useState}from'react';import{PanResponder,Pressable,SafeAreaView,StyleSheet,Text,View,useWindowDimensions}from'react-native';import{createGame,GameState,updateGame,Vec}from'./src/game';import{AsphaltBackdrop,SurvivorSprite,ZombieSprite}from'./src/visuals';import{WastelandScenery,PickupMarker,MuzzleFlash,ExplosionRing}from'./src/world';
const HUD=96;
export default function App(){const w=useWindowDimensions(),aw=Math.max(280,w.width),ah=Math.max(420,w.height-HUD);const[g,setG]=useState<GameState>(()=>createGame(aw,ah));const mv=useRef<Vec>({x:0,y:0}),origin=useRef<Vec|null>(null),sprint=useRef(false),dodge=useRef(false),grenade=useRef(false),drone=useRef(false);
useEffect(()=>setG(createGame(aw,ah)),[aw,ah]);useEffect(()=>{let prev=Date.now();const t=setInterval(()=>{const now=Date.now(),dt=Math.min(.05,(now-prev)/1000);prev=now;setG(s=>updateGame(s,{move:mv.current,sprint:sprint.current,dodge:dodge.current,grenade:grenade.current,drone:drone.current},dt));dodge.current=grenade.current=drone.current=false},33);return()=>clearInterval(t)},[]);
const pan=useMemo(()=>PanResponder.create({onStartShouldSetPanResponder:()=>true,onMoveShouldSetPanResponder:()=>true,onPanResponderGrant:e=>{origin.current={x:e.nativeEvent.pageX,y:e.nativeEvent.pageY}},onPanResponderMove:e=>{if(origin.current)mv.current={x:e.nativeEvent.pageX-origin.current.x,y:e.nativeEvent.pageY-origin.current.y}},onPanResponderRelease:()=>{mv.current={x:0,y:0};origin.current=null},onPanResponderTerminate:()=>{mv.current={x:0,y:0};origin.current=null}}),[]);
const reset=()=>{mv.current={x:0,y:0};setG(createGame(aw,ah))};const press=(r:React.MutableRefObject<boolean>)=>()=>{r.current=true};
return <SafeAreaView style={s.root}><View style={s.hud}><Text style={s.title}>DEADSHIFT</Text><Text style={s.stat}>W{g.wave}  HP {g.player.hp}</Text><Text style={s.stat}>AMMO {g.player.ammo}</Text><Text style={s.stat}>☠ {g.kills}</Text></View><View style={[s.arena,{width:aw,height:ah}]} {...pan.panHandlers}><AsphaltBackdrop/><WastelandScenery width={aw} height={ah}/>
{g.pickups.map(p=><View key={p.id} style={[s.pickup,{left:p.position.x-13,top:p.position.y-13}]}><PickupMarker kind={p.kind}/></View>)}
{g.zombies.map(z=><View key={z.id} style={{position:'absolute',left:z.position.x-z.radius-6,top:z.position.y-z.radius-6}}><ZombieSprite kind={z.kind} size={z.radius*2+12}/></View>)}
{g.bullets.length>0&&g.fireClock<.09&&<MuzzleFlash x={g.player.position.x+13} y={g.player.position.y-10}/>}
{g.droneFlash>0&&<ExplosionRing x={g.player.position.x} y={g.player.position.y} size={Math.min(220,130+g.droneFlash*180)}/>}
{g.bullets.map(b=><View key={b.id} style={[s.bullet,{left:b.position.x-3,top:b.position.y-3}]}/>)}
<View style={{position:'absolute',left:g.player.position.x-g.player.radius-6,top:g.player.position.y-g.player.radius-6}}><SurvivorSprite size={g.player.radius*2+12}/></View>
<View style={s.controls}><Pressable onPressIn={()=>sprint.current=true} onPressOut={()=>sprint.current=false} style={s.btn}><Text style={s.btnT}>SPRINT</Text></Pressable><Pressable onPress={press(dodge)} style={s.btn}><Text style={s.btnT}>ROLL</Text></Pressable><Pressable onPress={press(grenade)} style={s.btn}><Text style={s.btnT}>BOMB {g.player.grenades}</Text></Pressable><Pressable disabled={!g.droneCharges} onPress={press(drone)} style={[s.btn,!g.droneCharges&&s.disabled]}><Text style={s.btnT}>DRONE {g.droneCharges}</Text></Pressable></View>
<View style={s.stamina}><View style={[s.staminaFill,{width:`${g.player.stamina}%`}]} /></View>{g.droneFlash>0&&<View style={s.flash}/>}
{g.bossSpawned&&!g.bossDefeated&&<View pointerEvents="none" style={s.bossPanel}><Text style={s.warning}>THE BRUTE HAS ARRIVED</Text><View style={s.bossTrack}><View style={[s.bossHealth,{width:`${Math.max(0,Math.min(100,((g.zombies.find(z=>z.kind==='brute')?.hp??45)/45)*100))}%`}]}/></View><Text style={s.bossCaption}>WAVE 5 · BOSS ENCOUNTER</Text></View>}
{g.gameOver&&<View style={s.overlay}><Text style={s.over}>SHIFT OVER</Text><Text style={s.final}>Score {g.score} · Wave {g.wave} · Kills {g.kills}</Text><Pressable onPress={reset} style={s.restart}><Text style={s.restartT}>RUN IT BACK</Text></Pressable></View>}</View></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#08090b'},hud:{height:HUD,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:'#38221d'},title:{color:'#d9d9d9',fontWeight:'900',fontSize:17,letterSpacing:1.5,marginRight:'auto'},stat:{color:'#d7b8a8',fontWeight:'800',fontSize:12},arena:{position:'relative',overflow:'hidden',backgroundColor:'#15120f'},player:{position:'absolute',width:34,height:34,borderRadius:17,backgroundColor:'#3b3029',borderWidth:5,borderColor:'#bdb4a7'},scarf:{position:'absolute',width:20,height:7,backgroundColor:'#9d1e17',right:-8,top:5},zombie:{position:'absolute',backgroundColor:'#59604a',borderWidth:2,borderColor:'#81866a'},runner:{backgroundColor:'#73594b'},heavy:{backgroundColor:'#454c3d',borderWidth:4},brute:{backgroundColor:'#5b3028',borderColor:'#a14b39',borderWidth:5,alignItems:'center',justifyContent:'center'},bruteText:{fontSize:7,color:'#fff',fontWeight:'900'},bullet:{position:'absolute',width:6,height:6,borderRadius:3,backgroundColor:'#ffb52e'},pickup:{position:'absolute',width:26,height:26,borderRadius:5,backgroundColor:'#2a2925',borderWidth:2,borderColor:'#d08b35',alignItems:'center',justifyContent:'center'},pickText:{color:'#fff',fontWeight:'900'},controls:{position:'absolute',bottom:22,left:8,right:8,flexDirection:'row',gap:6,justifyContent:'center'},btn:{backgroundColor:'rgba(35,28,24,.92)',borderWidth:1,borderColor:'#a7492e',paddingHorizontal:10,paddingVertical:12,borderRadius:8},disabled:{opacity:.35},btnT:{color:'#eee',fontSize:10,fontWeight:'900'},stamina:{position:'absolute',left:10,top:10,width:90,height:6,backgroundColor:'#2b2b2b'},staminaFill:{height:6,backgroundColor:'#b78b42'},warning:{color:'#e35136',fontWeight:'900',fontSize:16,textAlign:'center'},bossPanel:{position:'absolute',top:22,left:45,right:45,padding:9,backgroundColor:'rgba(17,12,11,.88)',borderWidth:1,borderColor:'#8b3526',borderRadius:7},bossTrack:{height:9,backgroundColor:'#2a1715',borderRadius:5,overflow:'hidden',marginTop:6},bossHealth:{height:9,backgroundColor:'#d44b2d'},bossCaption:{color:'#e8bba5',fontSize:9,textAlign:'center',fontWeight:'800',marginTop:4},flash:{...StyleSheet.absoluteFill,backgroundColor:'rgba(255,110,30,.25)'},overlay:{...StyleSheet.absoluteFill,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(4,5,7,.88)'},over:{color:'#eee',fontSize:34,fontWeight:'900',letterSpacing:2},final:{color:'#bbb',marginTop:10,marginBottom:24},restart:{paddingHorizontal:22,paddingVertical:14,borderRadius:8,backgroundColor:'#a52a1f'},restartT:{color:'#fff',fontWeight:'900'}});
